services:
  - type: web
    name: face-insight-ai
    runtime: docker
    repo: https://github.com/prithvind/age-detector.git
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
